jobs:
  - name: sample-runsh-docker
    type: runSh
    allowPublicAccess: true
    steps:
      - IN: sample-test-script-docker
        showBuildStatus: true
      - IN: test-cli-docker-new
      #- IN: test-jfrogfile
    #  - IN: test-trigger01
      - TASK:
        - script: 'cd /build/IN/sample-test-script-docker/gitRepo'
        - script: 'docker pull shippabledocker/sample_node_pvt'
        - script: 'docker build -t=shippabledocker/hitchcock3_sample_node:runshnew  .'
        - script: 'docker push shippabledocker/hitchcock3_sample_node:runshnew'
   # flags: far
 
  - name: sample-runsh-docker-integration
    type: runSh
    allowPublicAccess: true
    steps:
      - IN: sample-test-script-docker
        showBuildStatus: true
      - IN: test-int-docker-new
      #- IN: test-jfrogfile
    #  - IN: test-trigger01
      - TASK:
        - script: echo $TESTINTDOCKERNEW_INTEGRATION_USERNAME
        - script: echo $TESTINTDOCKERNEW_INTEGRATION_PASSWORD
        - script: echo $TESTINTDOCKERNEW_INTEGRATION_EMAIL
        #- script: echo $DOCKERINTINT_INTEGRATION_URL
 
  - name: sample-runsh-docker-image
    type: runSh
    allowPublicAccess: true
    steps:
      - IN: sample-test-script-docker
        showBuildStatus: true
      - IN: sample_img_docker
     
      - TASK:
        - script: echo $SAMPLE_IMG_DOCKER_INTEGRATION_USERNAME
        - script: echo $SAMPLE_IMG_DOCKER_INTEGRATION_PASSWORD
        - script: echo $SAMPLE_IMG_DOCKER_INTEGRATION_EMAIL
        
        
  - name: manifest_dep
    type: manifest
    steps:
      - IN: sample-runsh-docker-image
      
      
  - name: docker_deploy
    type: deploy
    steps:
      - IN: manifest_dep
      - IN: ddc_cluster
      - IN: ddc_dopts
      #- IN: env-tripub
